openapi: 3.0.0
info:
  title: TheNoter app API
  description: API Documention for TheNoter App
  version: 1.0.0
servers:
  - url: http://localhost:8000/api

tags:
  - name: auth
    description: Auth
  - name: notes
    description: Заметки
  - name: tags
    description: Теги

paths:
  /auth/login:
    $ref: './auth/paths.yaml#/Login'
  /auth/register:
    $ref: './auth/paths.yaml#/Register'
  /auth/logout:
    $ref: './auth/paths.yaml#/Logout'

  /notes:
    $ref: './notes/paths.yaml#/CreateNote'
  /notes/{id}:
    $ref: './notes/paths.yaml#/CurrentNote'

  /tags:
    $ref: './tags/paths.yaml#/CreateAndAllTag'
  /tags/{id}:
    $ref: './tags/paths.yaml#/CurrentTag'

components:
  parameters:
    PathId:
      name: id
      in: path
      required: true
      description: Идентификатор ресурса
      schema:
        type: integer
    Include:
      name: include
      in: query
      required: false
      description: Список связанных ресурсов, разделенных запятыми, для включения
      schema:
        type: string
  responses:
    EmptyResponse:
      description: Пустой ответ
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                nullable: true
                example: null
    BadRequest:
      description: Неверный запрос.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: some bad request
              errors:
                type: object
                properties:
                  field_name:
                    type: array
                    items:
                      type: string
    Unauthenticated:
      description: Unauthenticated
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthenticated
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: some message
    ServerError:
      description: Внутренняя ошибка сервера.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: some error from server
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not found message

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []
